library(tidyverse)
library(janitor)
library(skimr)
acc_veh_2019<-read_csv("2019-gla-data-extract-vehicle.csv")
acc_atndt_2019<-read_csv("2019-gla-data-extract-attendant.csv")
acc_cslty_2019<-read_csv("2019-gla-data-extract-casualty.csv")
head(acc_veh_2019)
vehicle_type <-c("veh_code","veh_type")
veh_acc_1<-separate(acc_veh_2019,`Vehicle Type (Banded)`, vehicle_type, 2)
library(stringr)
drvr_sex<-c("sex_code","sex")
veh_acc_2<-separate(veh_acc_1,`Driver Sex`,drvr_sex,1)
view (veh_acc_2)
install.packages("DataCombine")
library(DataCombine)
str(veh_acc_2)
veh_acc_2$veh_type<- trimws(veh_acc_2$veh_type)
veh_acc_2$veh_code<- as.numeric(veh_acc_2$veh_code)
view(veh_acc_2)
res_code<-c("lane_code", "restricted_lane")
veh_acc_3<- separate(veh_acc_2,`Restricted Lane`,res_code,3)
veh_acc_3$lane_code <- as.numeric(veh_acc_3)
object <- c("object_code", "object_in_C/W")
veh_acc_3 <- separate(veh_acc_3,`Object in C/W`, object, 3)
veh_acc_3$object_code <- as.numeric(veh_acc_3$object_code)
veh_acc_3$restricted_lane <- trimws(veh_acc_3$restricted_lane)
veh_acc_3$`object_in_C/W` <- trimws(veh_acc_3$`object_in_C/W`)
view(veh_acc_3)
view(acc_atndt_2019)
severity <-c("severity_code", "acc_severity")
light_cond <- c("light_cond_code", "daylight_conditions")
wthr <- c("weather_code", "weather_conditions")
srfc <- c("surface_code", "road_conditions")
library(lubridate)
acc_atndt_2019$date <- format(strptime(acc_atndt_2019$`Accident Date`, format = "%d-%b-%y"), "%d/%m/%y" )
acc_atndt_2019$month <- format(as.Date(acc_atndt_2019$date),"%m")
view(acc_atndt_2019)
acc_atndt <- separate(acc_atndt_2019,`Accident Severity`, severity, 2)
acc_atndt <- separate(acc_atndt, `Light Conditions (Banded)`, light_cond, 2)
acc_atndt <- separate(acc_atndt, `Weather`, wthr, 2)
acc_atndt <- separate(acc_atndt, `Road Surface`,srfc,2)
acc_atndt$acc_severity <- trimws(acc_atndt$acc_severity)
acc_atndt$daylight_conditions <- trimws(acc_atndt$daylight_conditions)
acc_atndt$weather_conditions <- trimws(acc_atndt$weather_conditions)
acc_atndt$road_conditions <- trimws(acc_atndt$road_conditions)
accident_data <- veh_acc_3 %>%
  select(AREFNO, Borough, Northing, Easting, `Vehicle Ref.`, veh_type, restricted_lane, `object_in_C/W`, sex, `Driver Age`, `Driver Age (Banded)`)
skim(accident_data)
accident_report <- acc_atndt %>%
  select(AREFNO,Borough, Northing, Easting, acc_severity, `Accident Date`, month, daylight_conditions, weather_conditions, road_conditions)
skim(accident_report)
write.csv(accident_data,"accident_data.csv")
write.csv(accident_report,"accident_report.csv")
